server:
  port: 8899

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/foo
    username: root
    password: Root@1998


  redis:
    database: 12
    host: 172.17.0.1
    port: 6379

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false
file:
  local:
    path: /opt/file/upload

springdoc:
  packages-to-scan: fun.verda.SceneExample.module
  paths-to-match: /**/*


