server:
  port: 8899

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foo
    username: root
    password: Root@1995


  redis:
    database: 12
    password: 123456
    host: localhost
    port: 6379

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false
file:
  local:
    path: D:\nmydzx\upload

springdoc:
  packages-to-scan: fun.verda.SceneExample.module
  paths-to-match: /**/*

  swagger-ui:
    csrf:
      header-name: token

